export const LOGIN_PATIENT_REQUEST = "LOGIN_PATIENT_REQUEST";
export const LOGIN_PATIENT_ERROR = "LOGIN_PATIENT_ERROR";
export const LOGIN_PATIENT_SUCCESS = "LOGIN_PATIENT_SUCCESS";

export const LOGIN_DOCTOR_SUCCESS = "LOGIN_DOCTOR_SUCCESS";
export const LOGIN_DOCTOR_ERROR = "LOGIN_DOCTOR_ERROR";
export const LOGIN_DOCTOR_REQUEST = "LOGIN_DOCTOR_REQUEST";

export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_DOCTOR_SUCCESS = " REGISTER_DOCTOR_SUCCESS";
export const REGISTER_DOCTOR_ERROR = "REGISTER_DOCTOR_ERROR";
export const REGISTER_DOCTOR_REQUEST = "REGISTER_DOCTOR_REQUEST";

export const REGISTER_PATIENT_SUCCESS = " REGISTER_PATIENT_SUCCESS";
export const REGISTER_PATIENT_ERROR = "REGISTER_PATIENT_ERROR";
export const REGISTER_PATIENT_REQUEST = "REGISTER_PATIENT_REQUEST";

export const REGISTER_ADMIN_SUCCESS = " REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";
export const REGISTER_ADMIN_REQUEST = "REGISTER_ADMIN_REQUEST";

export const REGISTER_AMBULANCE_SUCCESS = " REGISTER_AMBULANCE_SUCCESS";
export const REGISTER_AMBULANCE_ERROR = "REGISTER_AMBULANCE_ERROR";
export const REGISTER_AMBULANCE_REQUEST = "REGISTER_AMBULANCE_REQUEST";

export const EDIT_PATIENT_SUCCESS = " EDIT_PATIENT_SUCCESS";
export const EDIT_PATIENT_ERROR = "EDIT_PATIENT_ERROR";
export const EDIT_PATIENT_REQUEST = "EDIT_PATIENT_REQUEST";

export const EDIT_DOCTOR_SUCCESS = " EDIT_DOCTOR_SUCCESS";
export const EDIT_DOCTOR_ERROR = "EDIT_DOCTOR_ERROR";
export const EDIT_DOCTOR_REQUEST = "EDIT_DOCTOR_REQUEST";

export const EDIT_ADMIN_SUCCESS = " EDIT_ADMIN_SUCCESS";
export const EDIT_ADMIN_ERROR = "EDIT_ADMIN_ERROR";
export const EDIT_ADMIN_REQUEST = "EDIT_ADMIN_REQUEST";

export const FORGET_PASSWORD_SUCCESS = " FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";

export const ADD_AVAILABLETIMES_REQUEST = "ADD_AVAILABLETIMES_REQUEST";
export const ADD_AVAILABLETIMES_ERROR = "ADD_AVAILABLETIMES_ERROR";
